### ISSUE TITLE
Merge into Rails?

### ISSUE THREAD

**Issue by caseyprovost** [toptal/database_validations#18]
What do you think about opening some of the behavior here as a PR against ActiveRecord or whatever relevant Rails core gem? Being as relationships are foundational to models I would think they would welcome any performance & logical enhancements to them.

**Comment by djezzzl** [comment]
Yes, I'm about to do it this weekend. I doubt they will accept it but we will try 👍 Anyway, we can use the solution as separate gem without any disadvantages against the integrated solution 👍

**Comment by djezzzl** [comment]
Just opened an issue: https://github.com/rails/rails/issues/34650

**Comment by djezzzl** [comment]
The Rails team won't accept the whole idea of the gem but they can merge a part of it. So I provided a PR: https://github.com/rails/rails/pull/34725.

**Comment by skatkov** [comment]
@djezzzl just trying to bring to your attention, that Rails core has shown interest in your initial PR and well bad that it never got finished.

per discussion here:
https://discuss.rubyonrails.org/t/validates-uniqueness-of-doesnt-really-guarantee-uniqueness/74398/2

**Comment by djezzzl** [comment]
Hey @skatkov, thank you for bringing this to me. I'll join the discussion.
