### ISSUE TITLE
Tasks for contribution

### ISSUE THREAD

**Issue by djezzzl** [toptal/database_validations#24]
Hi, **thank you** for using our gem! 

Here we have the list with opened tasks to do:
- [ ] Replace `where` option with `conditions` for `validates_db_uniqueness_of` so `validates_db_uniqueness_of` becomes easier replacement for `validates_uniqueness_of`. 

- [ ] Add `test coverage` analyzer to CI and badge to README

- [ ] Foreign keys can accept `NULL` values, so we can support `optional: true` option for `db_belongs_to`

- [ ] Add support of `Rails.application.config.active_record.belongs_to_required_by_default = false`

- [ ] Matchers `validates_presence_of` and `belong_to` should work 

*You can also suggest a new feature! Any contribution is welcome!*

**Comment by pirj** [comment]
No contributions needed? :)

**Comment by djezzzl** [comment]
Hey @pirj , nice to hear you 👍 

Yes, we need it and open to other ideas. I just want to move the list from `issues` because it's not about issues.
