### ISSUE TITLE
Running Specs

### ISSUE THREAD

**Issue by antarr** [toptal/database_validations#34]
How do I configure the database to run specs for this project.

**Comment by pirj** [comment]
@antarr Please take a look [here](https://github.com/toptal/database_validations#development).
In general, install both Postgres and MySQL, and create `database_validations_test` in both of them.
The database should be available to the DB user matching your system user (e.g. `antarr`). This should in general work out of the box on a Mac.
Let me know if it works for you, and please provide additional information about your system configuration if it doesn't.
