### ISSUE TITLE
db_belongs_to with optional: true

### ISSUE THREAD

**Issue by tarboy** [toptal/database_validations#40]
`db_belongs_to :company, optional: true`
gives a validation error:
ActiveRecord::RecordInvalid: Validation failed: Company must exist
on empty value (company_id=nil), although
`belongs_to :company, optional: true`
in the same situation does not give an error

**Comment by djezzzl** [comment]
Hi @tarboy, unfortunately, `optional: true` is not supported for `db_belongs_to`. Besides, it will be supported soon.
