### ISSUE TITLE
'bd_belong_to' doesn't work with  'optional: true'

### ISSUE THREAD

**Issue by dnhlinh** [toptal/database_validations#46]
While using `db_belong_to` with `optional: true`, it triggers a validation error `prohibited this service from being saved`.
Need to change `db_belong_to` to `belong_to` to associate with `optional: true`

**Comment by djezzzl** [comment]
Hey @dnhlinh,

Unfortunately, `db_belongs_to` doesn't support `optional: true` option. All supported options are listed here: https://github.com/toptal/database_validations#configuration-options.

**Comment by mpapis** [comment]
@djezzzl hey ;) is there anything blocking from making the optional work? we could use this one :D do you need any help on it?

**Comment by djezzzl** [comment]
Hi @mpapis, nice to hear you 👍 AFAIR, there is not that much to do. We basically need to update validator to allow `nil` values. I'll try to do that on my weekends. Or if you want you can try and I can help 👍
