### ISSUE TITLE
Testing case_sensitive: true

### ISSUE THREAD

**Issue by raivil** [toptal/database_validations#47]
Hey,

How can I test on RSpec if  `validate_db_uniqueness_of` is `case_sensitive: true`?

The matcher at https://github.com/toptal/database_validations/blob/master/lib/database_validations/rspec/uniqueness_validator_matcher.rb#L10 only has options for case insensitive.

Checking the diff from version 0.8.10 to latest master, the default for Rails 6 `case_sensitive` is nil.
https://github.com/toptal/database_validations/compare/v0.8.10...master#diff-0b72b6ffa59687cb5bb851b40f2ad87aR62
This causes all specs to fail if the validation is `case_sensitive: true`.

is this a limitation of the matcher? Are there plans to improve it?

Any help is appreciated.

Best Regards,
Ronaldo.

**Comment by djezzzl** [comment]
Hi @raivil,

Thank you for pointing this out. If we add `case_sensitive` modifier to the matcher, will it resolve the issue? Did I get it correct?

**Comment by raivil** [comment]
hey @djezzzl , yes, that's the case.
With the new changes related to Rails 6, the rspec matcher is not covering all possible scenarios. It covers the default value of `nil'` and `case INsensitive`. There's no way to specify test validation if `case_sensitive: true`.

**Comment by djezzzl** [comment]
Understand, are you interested in making a PR fixing that?

**Comment by raivil** [comment]
@djezzzl Unfortunately, I don't have the bandwidth to deal with that at the moment.

**Comment by djezzzl** [comment]
Hey, please try out `0.9.1` version and let me know if it doesn't help you. Feel free to reopen the issue if needed 👍
