### ISSUE TITLE
Idea: Replace `dependent: :delete`/`dependent: :nullify` with FK `on_delete:`/`on_update:`

### ISSUE THREAD

**Issue by pirj** [toptal/database_validations#59]
Hey @djezzzl ! :wave: 

Cascade deletion is sometimes a very expensive operation.
In case the association is defined as `dependent: :delete`, it is possible to rely on the database to perform the deletion instead.
See [`:on_delete`/`:on_update`](https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key).

Disclaimer: I clearly understand that `dependent: :destroy` should remain ignored, as [`destroy` also runs callbacks](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroy).

Would it make sense to detect this and suggest changing the FK in such a way that the DB handles cascade deletion/nullification?

Sorry for not being verbose. I'd love to validate the idea with you first, and elaborate if you support it.

**Comment by pirj** [comment]
> confused the gem with database_consistency.

100% guilty. Do you want me to open an issue there and close this one, or can you transfer it there?

> Would you like to contribute with such idea?

Absolutely. On my current project, we're going through the process of enforcing consistency, but it's not something that happens overnight. I'll surely be happy to improve the topic when I'm out of other things that `database_consistency` can detect. Might be earlier, but no promises.

**Comment by pirj** [comment]
Moved to https://github.com/djezzzl/database_consistency/issues/91

**Comment by djezzzl** [comment]
> 100% guilty. Do you want me to open an issue there and close this one, or can you transfer it there?

It's up to you 👍 As I'd like to see a PR some day 😄 

> Absolutely. On my current project, we're going through the process of enforcing consistency, but it's not something that happens overnight. I'll surely be happy to improve the topic when I'm out of other things that database_consistency can detect. Might be earlier, but no promises.

Thank you, take your time 👍 And let me know if you would need any help with that.
